# Generated by Django 4.0.6 on 2022-07-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company',
            new_name='user',
        ),
    ]
